services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
