CREATE TABLE IF NOT EXISTS "order_table" (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    total_amount DOUBLE PRECISION NOT NULL,
    total_discount_amount DOUBLE PRECISION NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    unique(id)
);