CREATE TABLE IF NOT EXISTS "order_detail_table" (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_name varchar(255) DEFAULT NULL,
    product_quantity DOUBLE PRECISION NULL DEFAULT NULL,
    product_price DOUBLE PRECISION NULL DEFAULT NULL,
    product_discount DOUBLE PRECISION NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (order_id) REFERENCES "order_table" (id) ON DELETE CASCADE
);